# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.2.1'

  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true

- task: Npm@1
  displayName: 'npm run build production build'
  inputs:
    command: custom
    verbose: true
    customCommand: 'run build-prod'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.BinariesDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: dist/*
    TargetFolder: '$(Build.BinariesDirectory)/dist'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.BinariesDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: wwwroot/*
    TargetFolder: '$(Build.BinariesDirectory)/wwwroot'
    CleanTargetFolder: true
    OverWrite: true

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
